spring:
  application:
    name: crland-oauth-server-psp-local
---
server:
  port: 8010
  context-path: /oauth

eureka:
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/info
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://txeureka-uat.saas.crland.com.cn/eureka/

---
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 60000
    pool:
      maxActive: -1
      maxIdle: 32
      maxWait: 30000
      minIdle: 8


security:
  sessions: stateless
  ignored:
   - /health
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

oauth:
  client:
    name: client
    secret: secret
    authorities: ROLE_USER
    validitySeconds: 43200
  user:
      url: http://127.0.0.1:8010/oauth/user
  token:
      url: http://127.0.0.1:8010/oauth/oauth/token

thymeleaf:  # html模板
  mode: LEGACYHTML5
  prefix: classpath:/templates/
  content-type: text/html
  suffix: .html

endpoints:
  sensitive: false

psp:
  getUserInfo: http://psp.crland.com.cn/user/list

front:
  logoutUrlPrefix: http://portaluat.crc.com.cn/oamsso/logout.html?end_url=
  iconUrlPrefix: http://static.saas.crland.com.cn/images/ui-icon/
  config:
    tech-platform-ui:
      url: http://10.72.57.71:3000
      title: "前端框架"
#      icon: false

limit:
  timeout: 10   # 锁定时间，单位min
  times: 5      # 登录错误次数


