server:
  port : 8181

spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cloud:
  config:
    server:
      git:
        uri: https://github.com/Snipermars/JavaLearning
        search-paths: configs
        username: Snipermars #账号密码写真实的快一些我觉得，不使用也能访问有点慢
        password: lpd.com312

