server:
  port : 8181

spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

cloud:
  config:
    server:
      git:
        uri: https://github.com/Snipermars/JavaLearning
        search-paths: configs

environment:
  prod